team_id_to_abbr = {
    108: 'LAA',
    109: 'ARI',
    110: 'BAL',
    111: 'BOS',
    112: 'CHC',
    113: 'CIN',
    114: 'CLE',
    115: 'COL',
    116: 'DET',
    117: 'HOU',
    118: 'KCR',
    119: 'LAD',
    120: 'WSH',
    121: 'NYM',
    133: 'ATH',
    134: 'PIT',
    135: 'SDP',
    136: 'SEA',
    137: 'SFG',
    138: 'STL',
    139: 'TBR',
    140: 'TEX',
    141: 'TOR',
    142: 'MIN',
    143: 'PHI',
    144: 'ATL',
    145: 'CWS',
    146: 'MIA',
    147: 'NYY',
    158: 'MIL',
}

bad_abbr_to_good_abbr = {
    'LAA': 'LAA',
    'AZ' : 'ARI',
    'BAL': 'BAL',
    'BOS': 'BOS',
    'CHC': 'CHC',
    'CIN': 'CIN',
    'CLE': 'CLE',
    'COL': 'COL',
    'DET': 'DET',
    'HOU': 'HOU',
    'KC' : 'KCR',
    'LAD': 'LAD',
    'WSH': 'WSH',
    'NYM': 'NYM',
    'OAK': 'ATH',
    'ATH': 'ATH',
    'PIT': 'PIT',
    'SD' : 'SDP',
    'SEA': 'SEA',
    'SF' : 'SFG',
    'STL': 'STL',
    'TB' : 'TBR',
    'TEX': 'TEX',
    'TOR': 'TOR',
    'MIN': 'MIN',
    'PHI': 'PHI',
    'ATL': 'ATL',
    'CWS': 'CWS',
    'MIA': 'MIA',
    'NYY': 'NYY',
    'MIL': 'MIL',
}

team_name_to_abbr = {
    'Phillies'  : 'PHI',
    'Cardinals' : 'STL',
    'Angels'    : 'LAA',
    'Giants'    : 'SFG',
    'Mets'      : 'NYM',
    'Dodgers'   : 'LAD',
    'Astros'    : 'HOU',
    'Reds'      : 'CIN',
    'Tigers'    : 'DET',
    'Braves'    : 'ATL',
    'Orioles'   : 'BAL',
    'White Sox' : 'CWS',
    'Rays'      : 'TBR',
    'Brewers'   : 'MIL',
    'Padres'    : 'SDP',
    'Guardians' : 'CLE',
    'D-backs'   : 'ARI',
    'Cubs'      : 'CHC',
    'Pirates'   : 'PIT',
    'Twins'     : 'MIN',
    'Yankees'   : 'NYY',
    'Rangers'   : 'TEX',
    'Royals'    : 'KCR',
    'Red Sox'   : 'BOS',
    'Blue Jays' : 'TOR',
    'Athletics' : 'ATH',
    'Oakland'   : 'ATH',
    'Marlins'   : 'MIA',
    'Mariners'  : 'SEA',
    'Rockies'   : 'COL',
    'Nationals' : 'WSH'
}

bref_abbr_to_abbr = {
    'ARI': 'ARI',
    'ATH': 'ATH',
    'ATL': 'ATL',
    'BAL': 'BAL',
    'BOS': 'BOS',
    'CHC': 'CHC',
    'CHW': 'CWS',
    'CWS': 'CWS',
    'CIN': 'CIN',
    'CLE': 'CLE',
    'COL': 'COL',
    'DET': 'DET',
    'HOU': 'HOU',
    'KCR': 'KCR',
    'LAA': 'LAA',
    'LAD': 'LAD',
    'MIA': 'MIA',
    'MIL': 'MIL',
    'MIN': 'MIN',
    'NYM': 'NYM',
    'NYY': 'NYY',
    'OAK': 'ATH',
    'PHI': 'PHI',
    'PIT': 'PIT',
    'SDP': 'SDP',
    'SEA': 'SEA',
    'SFG': 'SFG',
    'STL': 'STL',
    'TBR': 'TBR',
    'TEX': 'TEX',
    'TOR': 'TOR',
    'WSN': 'WSH',
}

fg_abbr_to_abbr = {
    'ARI': 'ARI',
    'ATH': 'ATH',
    'ATL': 'ATL',
    'BAL': 'BAL',
    'BOS': 'BOS',
    'CHC': 'CHC',
    'CHW': 'CWS',
    'CIN': 'CIN',
    'CLE': 'CLE',
    'COL': 'COL',
    'DET': 'DET',
    'HOU': 'HOU',
    'KCR': 'KCR',
    'LAA': 'LAA',
    'LAD': 'LAD',
    'MIA': 'MIA',
    'MIL': 'MIL',
    'MIN': 'MIN',
    'NYM': 'NYM',
    'NYY': 'NYY',
    'OAK': 'ATH',
    'PHI': 'PHI',
    'PIT': 'PIT',
    'SDP': 'SDP',
    'SEA': 'SEA',
    'SFG': 'SFG',
    'STL': 'STL',
    'TBR': 'TBR',
    'TEX': 'TEX',
    'TOR': 'TOR',
    'WSN': 'WSH',
}

abbr_to_lg = {
    'ARI': 'NL',
    'ATH': 'AL',
    'ATL': 'NL',
    'BAL': 'AL',
    'BOS': 'AL',
    'CHC': 'NL',
    'CWS': 'AL',
    'CIN': 'NL',
    'CLE': 'AL',
    'COL': 'NL',
    'DET': 'AL',
    'HOU': 'AL',
    'KCR': 'AL',
    'LAA': 'AL',
    'LAD': 'NL',
    'MIA': 'NL',
    'MIL': 'NL',
    'MIN': 'AL',
    'NYM': 'NL',
    'NYY': 'AL',
    'ATH': 'AL',
    'PHI': 'NL',
    'PIT': 'NL',
    'SDP': 'NL',
    'SEA': 'AL',
    'SFG': 'NL',
    'STL': 'NL',
    'TBR': 'AL',
    'TEX': 'AL',
    'TOR': 'AL',
    'WSH': 'NL',
}

sis_abbr_to_abbr = {
    'ARI': 'ARI',
    'ATH': 'ATH',
    'ATL': 'ATL',
    'BAL': 'BAL',
    'BOS': 'BOS',
    'CHC': 'CHC',
    'CHW': 'CWS',
    'CIN': 'CIN',
    'CLE': 'CLE',
    'COL': 'COL',
    'DET': 'DET',
    'HOU': 'HOU',
    'KCR': 'KCR',
    'LAA': 'LAA',
    'LAD': 'LAD',
    'MIA': 'MIA',
    'MIL': 'MIL',
    'MIN': 'MIN',
    'NYM': 'NYM',
    'NYY': 'NYY',
    'OAK': 'ATH',
    'PHI': 'PHI',
    'PIT': 'PIT',
    'SDP': 'SDP',
    'SEA': 'SEA',
    'SFG': 'SFG',
    'STL': 'STL',
    'TBR': 'TBR',
    'TEX': 'TEX',
    'TOR': 'TOR',
    'WSN': 'WSH',
}

