import numpy as np, polars as pl
from .abbr_standardization import *
cl = pl.col

def standardize_statcast(df):
    return df.with_columns(
        season = cl('game_year').cast(pl.Int32),
        team_abbr = pl.when(cl('inning_topbot').eq('Top'))
                      .then('home_team')
                      .otherwise('away_team')
                      .replace(bad_abbr_to_good_abbr),
        pitcher = cl('pitcher').cast(pl.Int64),
        game_date = cl('game_date').cast(pl.Date),
    )

def standardize_sprint_speed(df):
    return df.with_columns(
        season = cl('year').cast(pl.Int32),
        runner = cl('player_id').cast(pl.Int64),
        team_abbr = cl('team').replace(bad_abbr_to_good_abbr)
    )

def standardize_pitcher_defence(df):
    return df.with_columns(
        season = cl('year').cast(pl.Int32),
        pitcher = cl('entity_id').cast(pl.Int64),
        team_abbr = pl.lit(None, dtype=pl.Utf8),
        outs_above_average = cl('outs_above_average').cast(pl.Float64),
        fielding_runs_prevented = cl('fielding_runs_prevented').cast(pl.Float64),
    )

def standardize_player_bios(df):
    return df.with_columns(
        pitcher = cl('id').cast(pl.Int64),
    )

def standardize_pitcher_run_game(df):
    return df.with_columns(
        season = cl('start_year').cast(pl.Int32),
        pitcher = cl('entity_id').cast(pl.Int64),
        team_abbr = cl('team_name').replace(bad_abbr_to_good_abbr)
    )

def standardize_baseball_reference(df):
    return df.with_columns(
        season = cl('year_ID').cast(pl.Int32),
        pitcher = cl('mlb_ID').cast(pl.Int64),
        team_abbr = cl('team_ID').replace(bref_abbr_to_abbr),
    )

def standardize_fangraphs(df):
    return df.with_columns(
        season = cl('Season').cast(pl.Int32),
        pitcher = cl('xMLBAMID').cast(pl.Int64),
        team_abbr = cl('TeamNameAbb').replace(fg_abbr_to_abbr)
    )

def standardize_positioning_runs(df):
    return df.with_columns(
        team_abbr = cl('Team').replace(sis_abbr_to_abbr),
        season = cl('Year').cast(pl.Int32),
        positioning_runs = cl('Positioning'),
    ).select('season','team_abbr','positioning_runs')

insane_fg_schema = {
    'Throws': str,
    'xMLBAMID': int,
    'Name': str,
    'Team': str,
    'Season': int,
    'Age': float,
    'AgeR': str,
    'SeasonMin': int,
    'SeasonMax': int,
    'W': float,
    'L': float,
    'ERA': float,
    'G': float,
    'GS': float,
    'QS': float,
    'CG': float,
    'ShO': float,
    'SV': float,
    'BS': float,
    'IP': float,
    'TBF': float,
    'H': float,
    'R': float,
    'ER': float,
    'HR': float,
    'BB': float,
    'IBB': float,
    'HBP': float,
    'WP': float,
    'BK': float,
    'SO': float,
    'GB': float,
    'FB': float,
    'LD': float,
    'IFFB': float,
    'Pitches': float,
    'Balls': float,
    'Strikes': float,
    'RS': float,
    'IFH': float,
    'BU': float,
    'BUH': float,
    'K/9': float,
    'BB/9': float,
    'K/BB': float,
    'H/9': float,
    'HR/9': float,
    'AVG': float,
    'WHIP': float,
    'BABIP': float,
    'LOB%': float,
    'FIP': float,
    'GB/FB': float,
    'LD%': float,
    'GB%': float,
    'FB%': float,
    'IFFB%': float,
    'HR/FB': float,
    'IFH%': float,
    'BUH%': float,
    'TTO%': float,
    'CFraming': float,
    'Starting': float,
    'Start-IP': float,
    'Relieving': float,
    'Relief-IP': float,
    'RAR': float,
    'WAR': float,
    'Dollars': float,
    'RA9-Wins': float,
    'LOB-Wins': float,
    'BIP-Wins': float,
    'BS-Wins': float,
    'tERA': float,
    'xFIP': float,
    'WPA': float,
    '-WPA': float,
    '+WPA': float,
    'RE24': float,
    'REW': float,
    'pLI': float,
    'inLI': float,
    'gmLI': float,
    'exLI': float,
    'Pulls': float,
    'Games': float,
    'WPA/LI': float,
    'Clutch': float,
    'FB%1': float,
    'FBv': float,
    'SL%': float,
    'SLv': float,
    'CT%': float,
    'CTv': float,
    'CB%': float,
    'CBv': float,
    'CH%': float,
    'CHv': float,
    'SF%': float,
    'SFv': float,
    'KN%': float,
    'KNv': float,
    'XX%': float,
    'PO%': str,
    'wFB': float,
    'wSL': float,
    'wCT': float,
    'wCB': float,
    'wCH': float,
    'wSF': float,
    'wKN': float,
    'wFB/C': float,
    'wSL/C': float,
    'wCT/C': float,
    'wCB/C': float,
    'wCH/C': float,
    'wSF/C': float,
    'wKN/C': float,
    'O-Swing%': float,
    'Z-Swing%': float,
    'Swing%': float,
    'O-Contact%': float,
    'Z-Contact%': float,
    'Contact%': float,
    'Zone%': float,
    'F-Strike%': float,
    'SwStr%': float,
    'CStr%': float,
    'C+SwStr%': float,
    'HLD': float,
    'SD': float,
    'MD': float,
    'ERA-': float,
    'FIP-': float,
    'xFIP-': float,
    'K%': float,
    'BB%': float,
    'K-BB%': float,
    'SIERA': float,
    'kwERA': float,
    'RS/9': float,
    'E-F': float,
    'Pull': float,
    'Cent': float,
    'Oppo': float,
    'Soft': float,
    'Med': float,
    'Hard': float,
    'bipCount': float,
    'Pull%': float,
    'Cent%': float,
    'Oppo%': float,
    'Soft%': float,
    'Med%': float,
    'Hard%': float,
    'K/9+': float,
    'BB/9+': float,
    'K/BB+': float,
    'H/9+': float,
    'HR/9+': float,
    'AVG+': float,
    'WHIP+': float,
    'BABIP+': float,
    'LOB%+': float,
    'K%+': float,
    'BB%+': float,
    'LD%+': float,
    'GB%+': float,
    'FB%+': float,
    'HRFB%+': float,
    'Pull%+': float,
    'Cent%+': float,
    'Oppo%+': float,
    'Soft%+': float,
    'Med%+': float,
    'Hard%+': float,
    'xERA': float,
    'pb_o_CH': float,
    'pb_s_CH': float,
    'pb_c_CH': float,
    'pb_o_CU': float,
    'pb_s_CU': float,
    'pb_c_CU': float,
    'pb_o_FF': float,
    'pb_s_FF': float,
    'pb_c_FF': float,
    'pb_o_SI': float,
    'pb_s_SI': float,
    'pb_c_SI': float,
    'pb_o_SL': float,
    'pb_s_SL': float,
    'pb_c_SL': float,
    'pb_o_KC': float,
    'pb_s_KC': float,
    'pb_c_KC': float,
    'pb_o_FC': float,
    'pb_s_FC': float,
    'pb_c_FC': float,
    'pb_o_FS': float,
    'pb_s_FS': float,
    'pb_c_FS': float,
    'pb_overall': float,
    'pb_stuff': float,
    'pb_command': float,
    'pb_xRV100': float,
    'pb_ERA': float,
    'sp_s_CH': float,
    'sp_l_CH': float,
    'sp_p_CH': float,
    'sp_s_CU': float,
    'sp_l_CU': float,
    'sp_p_CU': float,
    'sp_s_FF': float,
    'sp_l_FF': float,
    'sp_p_FF': float,
    'sp_s_SI': float,
    'sp_l_SI': float,
    'sp_p_SI': float,
    'sp_s_SL': float,
    'sp_l_SL': float,
    'sp_p_SL': float,
    'sp_s_KC': float,
    'sp_l_KC': float,
    'sp_p_KC': float,
    'sp_s_FC': float,
    'sp_l_FC': float,
    'sp_p_FC': float,
    'sp_s_FS': float,
    'sp_l_FS': float,
    'sp_p_FS': float,
    'sp_s_FO': float,
    'sp_l_FO': float,
    'sp_p_FO': float,
    'sp_stuff': float,
    'sp_location': float,
    'sp_pitching': float,
    'PPTV': float,
    'CPTV': float,
    'BPTV': float,
    'DSV': float,
    'DGV': float,
    'BTV': float,
    'rPPTV': float,
    'rCPTV': float,
    'rBPTV': float,
    'rDSV': float,
    'rDGV': float,
    'rBTV': float,
    'EBV': float,
    'ESV': float,
    'rFTeamV': float,
    'rBTeamV': float,
    'rTV': float,
    'pfxFA%': float,
    'pfxFT%': str,
    'pfxFC%': float,
    'pfxFS%': float,
    'pfxFO%': float,
    'pfxSI%': float,
    'pfxSL%': float,
    'pfxCU%': float,
    'pfxKC%': float,
    'pfxEP%': float,
    'pfxCH%': float,
    'pfxSC%': float,
    'pfxKN%': float,
    'pfxUN%': str,
    'pfxvFA': float,
    'pfxvFT': str,
    'pfxvFC': float,
    'pfxvFS': float,
    'pfxvFO': float,
    'pfxvSI': float,
    'pfxvSL': float,
    'pfxvCU': float,
    'pfxvKC': float,
    'pfxvEP': float,
    'pfxvCH': float,
    'pfxvSC': float,
    'pfxvKN': float,
    'pfxFA-X': float,
    'pfxFT-X': str,
    'pfxFC-X': float,
    'pfxFS-X': float,
    'pfxFO-X': float,
    'pfxSI-X': float,
    'pfxSL-X': float,
    'pfxCU-X': float,
    'pfxKC-X': float,
    'pfxEP-X': float,
    'pfxCH-X': float,
    'pfxSC-X': float,
    'pfxKN-X': float,
    'pfxFA-Z': float,
    'pfxFT-Z': str,
    'pfxFC-Z': float,
    'pfxFS-Z': float,
    'pfxFO-Z': float,
    'pfxSI-Z': float,
    'pfxSL-Z': float,
    'pfxCU-Z': float,
    'pfxKC-Z': float,
    'pfxEP-Z': float,
    'pfxCH-Z': float,
    'pfxSC-Z': float,
    'pfxKN-Z': float,
    'pfxwFA': float,
    'pfxwFT': str,
    'pfxwFC': float,
    'pfxwFS': float,
    'pfxwFO': float,
    'pfxwSI': float,
    'pfxwSL': float,
    'pfxwCU': float,
    'pfxwKC': float,
    'pfxwEP': float,
    'pfxwCH': float,
    'pfxwSC': float,
    'pfxwKN': float,
    'pfxwFA/C': float,
    'pfxwFT/C': str,
    'pfxwFC/C': float,
    'pfxwFS/C': float,
    'pfxwFO/C': float,
    'pfxwSI/C': float,
    'pfxwSL/C': float,
    'pfxwCU/C': float,
    'pfxwKC/C': float,
    'pfxwEP/C': float,
    'pfxwCH/C': float,
    'pfxwSC/C': float,
    'pfxwKN/C': float,
    'pfxO-Swing%': float,
    'pfxZ-Swing%': float,
    'pfxSwing%': float,
    'pfxO-Contact%': float,
    'pfxZ-Contact%': float,
    'pfxContact%': float,
    'pfxZone%': float,
    'pfxPace': float,
    'piCH%': float,
    'piCS%': float,
    'piCU%': float,
    'piFA%': float,
    'piFC%': float,
    'piFS%': float,
    'piKN%': float,
    'piSB%': float,
    'piSI%': float,
    'piSL%': float,
    'piXX%': float,
    'pivCH': float,
    'pivCS': float,
    'pivCU': float,
    'pivFA': float,
    'pivFC': float,
    'pivFS': float,
    'pivKN': float,
    'pivSB': float,
    'pivSI': float,
    'pivSL': float,
    'pivXX': float,
    'piCH-X': float,
    'piCS-X': float,
    'piCU-X': float,
    'piFA-X': float,
    'piFC-X': float,
    'piFS-X': float,
    'piKN-X': float,
    'piSB-X': float,
    'piSI-X': float,
    'piSL-X': float,
    'piXX-X': float,
    'piCH-Z': float,
    'piCS-Z': float,
    'piCU-Z': float,
    'piFA-Z': float,
    'piFC-Z': float,
    'piFS-Z': float,
    'piKN-Z': float,
    'piSB-Z': float,
    'piSI-Z': float,
    'piSL-Z': float,
    'piXX-Z': float,
    'piwCH': float,
    'piwCS': float,
    'piwCU': float,
    'piwFA': float,
    'piwFC': float,
    'piwFS': float,
    'piwKN': float,
    'piwSB': float,
    'piwSI': float,
    'piwSL': float,
    'piwXX': float,
    'piwCH/C': float,
    'piwCS/C': float,
    'piwCU/C': float,
    'piwFA/C': float,
    'piwFC/C': float,
    'piwFS/C': float,
    'piwKN/C': float,
    'piwSB/C': float,
    'piwSI/C': float,
    'piwSL/C': float,
    'piwXX/C': float,
    'piO-Swing%': float,
    'piZ-Swing%': float,
    'piSwing%': float,
    'piO-Contact%': float,
    'piZ-Contact%': float,
    'piContact%': float,
    'piZone%': float,
    'piPace': float,
    'Events': float,
    'EV': float,
    'LA': float,
    'Barrels': float,
    'Barrel%': float,
    'maxEV': float,
    'HardHit': float,
    'HardHit%': float,
    'Q': float,
    'TG': float,
    'TIP': float,
    'PlayerNameRoute': str,
    'PlayerName': str,
    'position': str,
    'TeamName': str,
    'TeamNameAbb': str,
    'teamid': int,
    'playerid': int,
    'EV90': float,
}

